apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::545220419294:role/eksctl-demo-cluster-nodegroup-ng-4-NodeInstanceRole-ZGz4xWqrJohC
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::545220419294:role/codebuild-flask-eks-role
      username: codebuild
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-15T11:27:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1184"
  uid: e7830e13-2ac6-448a-a23a-b2ab7e7a2d12